const express  = require("express");
const router   = express.Router();
const { getStats, getAllUsers, toggleUser, resetBalance } = require("../controllers/adminController");
const { protect, authorize } = require("../middleware/auth");
router.use(protect, authorize("admin"));
router.get("/stats", getStats);
router.get("/users", getAllUsers);
router.put("/users/:id/toggle", toggleUser);
router.put("/users/:id/reset", resetBalance);
module.exports = router;
