const express = require("express");
const router  = express.Router();
const { register, login, refreshToken, logout, getMe, updatePassword } = require("../controllers/authController");
const { protect }       = require("../middleware/auth");
const { registerRules, loginRules, validate } = require("../middleware/validators");
router.post("/register", registerRules, validate, register);
router.post("/login",    loginRules,    validate, login);
router.post("/refresh",  refreshToken);
router.post("/logout",   protect, logout);
router.get ("/me",       protect, getMe);
router.put ("/password", protect, updatePassword);
module.exports = router;
